name: imeditor
version: git
summary: Simple & versatile image editor.
description: >
  ImEditor, the image editor you need. An ingenious lightweight software...
  With ImEditor, the image editing finally becomes easy.
icon: imeditor/assets/imeditor.png
grade: devel
confinement: devmode

parts:
  imeditor:
    source: .
    plugin: python
    python-version: python3
    stage-packages:
      - python3-gi
      - python3-pil
      - gir1.2-gtk-3.0
      - gir1.2-gdkpixbuf-2.0
    after: [desktop-gtk3]
    override-prime: |
      set -eu
      snapcraftctl prime
      # Fix-up application icon lookup
      sed --in-place 's|^Icon=.*|Icon=\${SNAP}/meta/gui/icon.png|' usr/share/applications/imeditor.desktop

apps:
  imeditor:
    environment:
      DISABLE_WAYLAND: 1
    command: desktop-launch $SNAP/bin/imeditor.py
    desktop: usr/share/applications/imeditor.desktop
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - x11
